import { useAuth } from "../context/AuthContext";
import { useNavigate } from "react-router-dom";

const C = {
    bg: "#050810", card: "rgba(255,255,255,0.028)", bord: "rgba(255,255,255,0.08)",
    text: "#d0ccc4", muted: "rgba(208,204,196,0.45)", blue: "#5b9cf6", gold: "#e0a020",
};

export default function Landing() {
    const { user } = useAuth();
    const navigate = useNavigate();

    const card = (x = {}) => ({ background: C.card, border: `1px solid ${C.bord}`, borderRadius: 14, padding: 24, backdropFilter: "blur(4px)", ...x });
    const btn = (v = "p") => ({
        cursor: "pointer", border: "none", borderRadius: 9, fontFamily: "'Outfit',sans-serif", fontWeight: 600, fontSize: 14, padding: "11px 24px", transition: "all .16s",
        ...(v === "p" ? { background: "linear-gradient(135deg,#2563eb,#5b9cf6)", color: "#fff" }
            : v === "g" ? { background: "transparent", color: C.blue, border: `1px solid ${C.blue}44` }
                : { background: "rgba(255,255,255,0.05)", color: C.text, border: `1px solid ${C.bord}` }),
    });

    return (
        <div style={{ maxWidth: 1100, margin: "0 auto", padding: "90px 26px 80px" }}>
            <div style={{ textAlign: "center", marginBottom: 68 }}>
                <div className="up" style={{ fontSize: 11, letterSpacing: "0.28em", color: `${C.blue}88`, marginBottom: 20, textTransform: "uppercase" }}>
                    TF-IDF · Thompson Sampling · IRT · AI-Powered · MongoDB · GCP
                </div>
                <h1 className="up" style={{
                    fontFamily: "'Instrument Serif',serif", fontSize: 68, lineHeight: 1.0, marginBottom: 14,
                    background: `linear-gradient(130deg,${C.blue},#a5c8ff,${C.gold})`, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent",
                }}>
                    The Interview Engine<br />
                    <span style={{ fontStyle: "italic" }}>That Trains Itself</span>
                </h1>
                <p className="up" style={{ fontSize: 16, color: C.muted, maxWidth: 580, margin: "0 auto 16px", lineHeight: 1.88 }}>
                    Showcase your true potential. Questions are dynamically tailored to match your unique experience and the role you want.
                    Engage in a natural, adaptive conversation designed to <strong style={{ color: C.blue }}>highlight your strengths</strong> and get you hired.
                </p>
                <p className="up" style={{ fontSize: 13, color: "rgba(208,204,196,0.3)", marginBottom: 16, fontFamily: "'JetBrains Mono',monospace" }}>
                    Fair · Adaptive · Personalized · Real-time Feedback
                </p>
                <p className="up" style={{ fontSize: 13, color: "rgba(74,222,128,0.6)", marginBottom: 46, fontFamily: "'JetBrains Mono',monospace" }}>
                    🚀 NextGen-HR · Empowering Your Career Journey
                </p>
                <div className="up" style={{ display: "flex", gap: 14, justifyContent: "center" }}>
                    {user ? (
                        <button style={{ ...btn("p"), fontSize: 16, padding: "13px 36px" }}
                            onClick={() => navigate(user.role === "hr" ? "/hr/dashboard" : "/candidate/dashboard")}>
                            Go to Dashboard
                        </button>
                    ) : (
                        <>
                            <button style={{ ...btn("p"), fontSize: 16, padding: "13px 36px" }} onClick={() => navigate("/candidate/login")}>
                                Apply as Candidate
                            </button>
                            <button style={{ ...btn("g"), fontSize: 16, padding: "13px 36px" }} onClick={() => navigate("/hr/login")}>
                                HR Portal
                            </button>
                        </>
                    )}
                </div>
            </div>

            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(200px,1fr))", gap: 14 }}>
                {[
                    { icon: "◎", h: "Zero Pre-Labels", b: "Every question starts with b=0, a=1. Difficulty emerges from responses via online gradient descent. IRT parameters persist in MongoDB." },
                    { icon: "⟳", h: "Job-Driven Generation", b: "Topics extracted via TF-IDF. Questions generated by Gemini AI, tailored to any domain. Works for chefs, engineers, nurses — any job." },
                    { icon: "θ̂", h: "IRT Ability Scoring", b: "Candidate score = MLE estimate θ̂ via Newton-Raphson, weighted by Fisher information I(θ). All computed in the Python backend." },
                    { icon: "⚡", h: "Thompson Sampling", b: "Beta(α,β) posterior per question arm. Exploration automatic. Bandit selects most informative next question weighted by IRT info." },
                    { icon: "🔐", h: "Multi-User Portals", b: "Separate HR and Candidate accounts. HR only sees their own job postings and candidates. Resumes stored in GCP Cloud Storage." },
                ].map((c, i) => (
                    <div key={i} className="up" style={{ ...card({ padding: 20 }), animationDelay: `${i * 0.07}s` }}>
                        <div style={{ fontSize: 26, color: C.blue, marginBottom: 10 }}>{c.icon}</div>
                        <div style={{ fontSize: 14, fontWeight: 600, color: C.blue, marginBottom: 6 }}>{c.h}</div>
                        <div style={{ fontSize: 12.5, color: C.muted, lineHeight: 1.72 }}>{c.b}</div>
                    </div>
                ))}
            </div>
        </div>
    );
}
